pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('file list') {
      steps {
        sh 'pwd'
        sh 'ls'
      }
    }
    stage('enviroments') {
      steps {
        sh 'env;echo"fin";'
      }
    }
  }
}